### ISSUE TITLE
Unit tests do not compile

### ISSUE THREAD

**Issue by ghost** [awsdert/mitsy#2]
I attempted to update unit_tests.c so that it will compile using the latest code structure (filenames etc), but gave up in the attempt: too many errors. I could probably spend a lot of time and get it to work but maybe it's better to rewrite the file from scratch (?) to more accurately test the current state of the project. Not sure...

**Comment by awsdert** [comment]
Ah yeah, was still in middle of updating all the code after I changed the base header, I basically uploaded the whole project just cause I could when I was aiming to provide the source for the code I was creating threads about at the board, I'll leave this issue open for now since it is something I need to do later once I finish learning how to transform integer based fpn into actual floats, gonna put that little file into an online gdb project when I get a chance after an upcoming family event (burying grandma's ashe's). Just in case others were looking at just this issue and not the other one you created a thread for I'll point out my long response time was mostly down to my computer saying no after I rebooted after installing nvidia drivers (apparently even on manjaro, an arch linux based distro, nothing but the 390 variety reponds well to my card and it still doesn't provide vulkan properly despite saying it does)

**Comment by awsdert** [comment]
I think I will fix this tomorrow, now that I have some working logic to convert an FPN to a float I can add this while I'm at it and write the preliminary function for reading numbers, I'll also need to decide on how to return those values for the sake of expression optimisation (or simply getting final result for an #if statement)

**Comment by awsdert** [comment]
Alright the file is fixed, gotta add test data and test functions though so for now it merely compiles, haven't tried to run it yet so don't be too surprised if there happens to be a segmentation fault.

**Comment by awsdert** [comment]
With the recent changes the tests run to a point so as far as the compile issue goes I will consider this closed, the run time issue I will deal with later
